---

- name: Ensure we have our nfs utils module installed
  package:
    name: nfs-utils
    state: present

- name: Run our server configuration tasks
  include: server.yml
  when: is_nfs_server|default(false)
